import type { CustomKpi } from '@/src/types/app';
import type { PerformanceMetrics } from '@/src/types/performance';
import { formatCurrency } from '@/src/lib/performance';

export type InsightSeverity='critical'|'warning'|'opportunity'|'positive';
export interface ManagerInsight { id:string; title:string; detail:string; action:string; severity:InsightSeverity; score:number; }
export interface ManagerInsightInput { metrics:PerformanceMetrics; salesGoal:number; laborGoalPct:number|null; partsGoalPct:number|null; kpis:CustomKpi[]; }

function kpiGap(k:CustomKpi){if(k.monthly_goal===null||k.current_value===null||k.monthly_goal===0)return null;const delta=k.goal_direction==='higher'?(k.monthly_goal-k.current_value):(k.current_value-k.monthly_goal);return delta/k.monthly_goal;}
export function buildManagerInsights(input:ManagerInsightInput):ManagerInsight[]{const {metrics}=input;const out:ManagerInsight[]=[];
 if(input.salesGoal>0){
  if(metrics.projectedGoalPercent<90)out.push({id:'sales-critical',title:'Sales pace needs immediate attention',detail:`Current pace projects ${metrics.projectedGoalPercent.toFixed(1)}% of the monthly sales goal.`,action:`Build today's plan around at least ${formatCurrency(metrics.salesNeededPerRemainingDay)} per remaining selling day. Focus first on inspection quality, declined-work follow-up, and complete customer presentations.`,severity:'critical',score:100+(90-metrics.projectedGoalPercent)});
  else if(metrics.projectedGoalPercent<100)out.push({id:'sales-warning',title:'Close the sales pace gap',detail:`Current pace projects ${metrics.projectedGoalPercent.toFixed(1)}% of goal.`,action:`Protect a daily pace of ${formatCurrency(metrics.salesNeededPerRemainingDay)}. Review opportunities throughout the day rather than waiting until close.`,severity:'warning',score:85+(100-metrics.projectedGoalPercent)});
  else out.push({id:'sales-positive',title:'Protect the sales pace',detail:`Current pace projects ${metrics.projectedGoalPercent.toFixed(1)}% of goal.`,action:'Keep the process consistent and avoid sacrificing labor or parts discipline just to add sales.',severity:'positive',score:30});
 }
 if(input.laborGoalPct!==null&&metrics.laborPercent>input.laborGoalPct)out.push({id:'labor',title:'Labor is above goal',detail:`Labor is ${metrics.laborPercent.toFixed(2)}% versus a ${input.laborGoalPct.toFixed(2)}% goal.`,action:'Review controllable straight-time hours in the Labor Planner. Only reduce hours if workload allows; future work and sales impact are not assumed.',severity:metrics.laborPercent-input.laborGoalPct>=3?'critical':'warning',score:90+(metrics.laborPercent-input.laborGoalPct)*3});
 if(input.partsGoalPct!==null&&metrics.partsPercent>input.partsGoalPct)out.push({id:'parts',title:'Parts cost is above goal',detail:`Parts cost is ${metrics.partsPercent.toFixed(2)}% versus a ${input.partsGoalPct.toFixed(2)}% goal.`,action:'Audit high-dollar parts tickets, sourcing, pricing, credits and missed returns before changing selling behavior.',severity:metrics.partsPercent-input.partsGoalPct>=2?'critical':'warning',score:88+(metrics.partsPercent-input.partsGoalPct)*4});
 input.kpis.forEach(k=>{const gap=kpiGap(k);if(gap!==null&&gap>0.05)out.push({id:`kpi-${k.id}`,title:`${k.name} needs attention`,detail:`Current ${k.current_value} versus goal ${k.monthly_goal}.`,action:`Make ${k.name} visible in today's huddle and assign one concrete behavior to improve it.`,severity:gap>.2?'critical':'warning',score:70+Math.min(25,gap*50)});});
 if(metrics.sameDayYearOverYearPercent!==null&&metrics.sameDayYearOverYearPercent<-5)out.push({id:'yoy-sameday',title:'Behind last year at the same selling day',detail:`MTD sales are ${Math.abs(metrics.sameDayYearOverYearPercent).toFixed(1)}% behind last year at this same selling-day count.`,action:'Compare car count and ARO to determine whether the gap is primarily traffic, ticket value, or both before choosing the response.',severity:'opportunity',score:72+Math.min(15,Math.abs(metrics.sameDayYearOverYearPercent))});
 return out.sort((a,b)=>b.score-a.score).slice(0,3);}
