import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '@/src/lib/supabase';
import { getAssignment } from '@/src/lib/appData';
import { hasMinimumRole,type UserAssignment } from '@/src/types/app';

type PostType='announcement'|'recognition'|'discussion';
type HubPost={id:string;organization_id:string;district_id:string;store_id:string|null;author_user_id:string;post_type:PostType;title:string|null;body:string;created_at:string;stores?:{name:string;store_code:string|null}|null};
const db=()=>{if(!supabase)throw new Error('Supabase is not configured.');return supabase};
const err=(e:unknown)=>e instanceof Error?e.message:'Something went wrong.';
export default function HubScreen(){
 const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [assignment,setAssignment]=useState<UserAssignment|null>(null);const [posts,setPosts]=useState<HubPost[]>([]);const [type,setType]=useState<PostType>('discussion');const [title,setTitle]=useState('');const [body,setBody]=useState('');
 const canLead=assignment?hasMinimumRole(assignment.role,'district_manager'):false;
 const load=useCallback(async()=>{setLoading(true);try{const {data:{user},error}=await db().auth.getUser();if(error)throw error;if(!user)throw new Error('Sign in required.');const a=await getAssignment(user.id);if(!a?.district_id)throw new Error('A district assignment is required for the Hub.');setAssignment(a);const {data,error:postError}=await db().from('district_hub_posts').select('id,organization_id,district_id,store_id,author_user_id,post_type,title,body,created_at,stores:store_id(name,store_code)').eq('district_id',a.district_id).order('created_at',{ascending:false}).limit(100);if(postError)throw postError;setPosts((data??[]) as unknown as HubPost[]);}catch(e){Alert.alert('District Hub',err(e));}finally{setLoading(false);}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!canLead&&type!=='discussion')setType('discussion')},[canLead,type]);
 const options=useMemo<PostType[]>(()=>canLead?['discussion','announcement','recognition']:['discussion'],[canLead]);
 async function post(){if(!assignment?.district_id||!body.trim())return Alert.alert('Add a message','Write something before posting.');setSaving(true);try{const {data:{user}}=await db().auth.getUser();if(!user)throw new Error('Sign in required.');const {error}=await db().from('district_hub_posts').insert({organization_id:assignment.organization_id,district_id:assignment.district_id,store_id:assignment.store_id,author_user_id:user.id,post_type:type,title:title.trim()||null,body:body.trim()});if(error)throw error;setTitle('');setBody('');setType('discussion');await load();}catch(e){Alert.alert('Could not post',err(e));}finally{setSaving(false);}}
 if(loading)return <SafeAreaView style={st.center}><ActivityIndicator size="large"/></SafeAreaView>;
 return <SafeAreaView style={st.page}><View style={st.header}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={28}/></Pressable><View><Text style={st.eyebrow}>DISTRICT HUB</Text><Text style={st.headerTitle}>Team feed</Text></View></View><ScrollView contentContainerStyle={st.scroll} keyboardShouldPersistTaps="handled">
 <View style={st.card}><Text style={st.h}>Share with the district</Text><Text style={st.muted}>{canLead?'Post a discussion, announcement, or recognition.':'Ask for advice, share a tactic, or start an operational discussion.'}</Text><View style={st.chips}>{options.map(x=><Pressable key={x} onPress={()=>setType(x)} style={[st.chip,type===x&&st.chipOn]}><Text style={[st.chipText,type===x&&st.chipTextOn]}>{x[0].toUpperCase()+x.slice(1)}</Text></Pressable>)}</View>{type!=='discussion'?<TextInput style={st.input} value={title} onChangeText={setTitle} placeholder={type==='recognition'?'Recognition headline':'Announcement title'}/>:null}<TextInput style={[st.input,st.multiline]} value={body} onChangeText={setBody} placeholder="What should the district know?" multiline/><Pressable disabled={saving} onPress={()=>void post()} style={[st.button,saving&&st.disabled]}><Text style={st.buttonText}>{saving?'Posting…':'Post to District Hub'}</Text></Pressable></View>
 <Text style={st.section}>Latest</Text>{posts.map(p=><View key={p.id} style={st.card}><View style={st.postTop}><View style={st.flex}><Text style={st.tag}>{p.post_type.toUpperCase()}</Text>{p.title?<Text style={st.postTitle}>{p.title}</Text>:null}<Text style={st.meta}>{p.stores?`${p.stores.store_code?`${p.stores.store_code} · `:''}${p.stores.name} · `:''}{new Date(p.created_at).toLocaleString()}</Text></View>{p.post_type==='recognition'?<Ionicons name="trophy" size={24} color="#a86800"/>:p.post_type==='announcement'?<Ionicons name="megaphone" size={24} color="#1769e0"/>:<Ionicons name="chatbubble-ellipses" size={22} color="#667085"/>}</View><Text style={st.body}>{p.body}</Text></View>)}{!posts.length?<Text style={st.muted}>No posts yet. Start the district conversation above.</Text>:null}
 </ScrollView></SafeAreaView>;
}
const st=StyleSheet.create({page:{flex:1,backgroundColor:'#f5f7fb'},center:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:18,paddingVertical:12,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:'#e6eaf0'},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1.2,color:'#1769e0'},headerTitle:{fontSize:20,fontWeight:'800',color:'#172033'},scroll:{padding:18,paddingBottom:60,gap:14},card:{backgroundColor:'#fff',borderRadius:16,padding:16,gap:10,borderWidth:1,borderColor:'#e6eaf0'},h:{fontSize:18,fontWeight:'800',color:'#172033'},section:{fontSize:18,fontWeight:'800',color:'#172033',marginTop:4},muted:{color:'#667085',lineHeight:19},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:10,borderWidth:1,borderColor:'#d0d5dd'},chipOn:{backgroundColor:'#eaf2ff',borderColor:'#1769e0'},chipText:{fontWeight:'700',color:'#475467'},chipTextOn:{color:'#1769e0'},input:{borderWidth:1,borderColor:'#d0d5dd',borderRadius:10,paddingHorizontal:12,paddingVertical:11,fontSize:16},multiline:{minHeight:100,textAlignVertical:'top'},button:{backgroundColor:'#1769e0',borderRadius:10,padding:13,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},disabled:{opacity:.55},postTop:{flexDirection:'row',gap:10},flex:{flex:1},tag:{fontSize:11,fontWeight:'900',color:'#1769e0',letterSpacing:.8},postTitle:{fontSize:17,fontWeight:'800',color:'#172033',marginTop:3},meta:{color:'#98a2b3',fontSize:12,marginTop:4},body:{fontSize:15,color:'#344054',lineHeight:21}});
