import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { getAssignment,getEmployeeTimePlans,getEmployees,getLatestDaily,getMonthSettings,saveEmployeeTimePlan } from '@/src/lib/appData';
import { laborScenario } from '@/src/lib/laborPlanner';
import { supabase } from '@/src/lib/supabase';
import { canViewTeamWages,type Employee,type EmployeeTimePlan } from '@/src/types/app';
import { formatCurrency } from '@/src/lib/performance';

const date=()=>new Date().toISOString().slice(0,10); const ym=()=>({year:new Date().getFullYear(),month:new Date().getMonth()+1});
const num=(v:string)=>Math.max(0,Number(v)||0);
export default function LaborPlanner(){
 const [loading,setLoading]=useState(true);const [employees,setEmployees]=useState<Employee[]>([]);const [plans,setPlans]=useState<EmployeeTimePlan[]>([]);const [storeId,setStoreId]=useState('');const [mtdSales,setSales]=useState(0);const [mtdLabor,setLabor]=useState(0);const [goal,setGoal]=useState<number|null>(null);const [hours,setHours]=useState<Record<string,string>>({});const [actual,setActual]=useState<Record<string,string>>({});const [cutEmployee,setCutEmployee]=useState('');const [cutHours,setCutHours]=useState('0');const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{if(!supabase)throw new Error('Supabase is not configured.');const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error('Sign in required.');const a=await getAssignment(user.id);if(!a||!canViewTeamWages(a.role)||!a.store_id)throw new Error('Store Manager access with a store assignment is required.');setStoreId(a.store_id);const now=ym();const [e,p,d,s]=await Promise.all([getEmployees(a.store_id),getEmployeeTimePlans(a.store_id,date()),getLatestDaily(a.store_id,now.year,now.month),getMonthSettings(a.store_id,now.year,now.month)]);setEmployees(e);setPlans(p);setSales(Number(d?.mtd_sales??0));setLabor(Number(d?.labor_cost??0));setGoal(s?.labor_goal_pct===null||s?.labor_goal_pct===undefined?null:Number(s.labor_goal_pct));const h:Record<string,string>={},ac:Record<string,string>={};e.forEach(emp=>{const row=p.find(x=>x.employee_id===emp.id);h[emp.id]=String(row?.scheduled_hours??0);ac[emp.id]=row?.actual_hours===null||row?.actual_hours===undefined?'':String(row.actual_hours);});setHours(h);setActual(ac);if(!cutEmployee)setCutEmployee(e.find(x=>x.pay_type==='straight_hourly')?.id??'');}catch(e){Alert.alert('Labor Planner',e instanceof Error?e.message:'Could not load planner.');}finally{setLoading(false);}},[cutEmployee]);
 useEffect(()=>{void load();},[load]);
 const selected=employees.find(e=>e.id===cutEmployee);const scenario=useMemo(()=>laborScenario({currentMtdLaborCost:mtdLabor,mtdSales,cutHours:num(cutHours),hourlyRate:selected?.pay_type==='straight_hourly'?Number(selected.pay_rate):0,goalPct:goal}),[mtdLabor,mtdSales,cutHours,selected,goal]);
 async function save(){setSaving(true);try{await Promise.all(employees.map(e=>saveEmployeeTimePlan({employee_id:e.id,store_id:storeId,work_date:date(),scheduled_hours:num(hours[e.id]??'0'),actual_hours:(actual[e.id]??'').trim()===''?null:num(actual[e.id])})));Alert.alert('Saved','Today’s staffing plan is saved.');await load();}catch(e){Alert.alert('Save failed',e instanceof Error?e.message:'Could not save.');}finally{setSaving(false);}}
 if(loading)return <SafeAreaView style={st.center}><ActivityIndicator size="large"/></SafeAreaView>;
 return <SafeAreaView style={st.page}><View style={st.header}><Pressable onPress={()=>router.back()}><Text style={st.back}>‹ Team</Text></Pressable><Text style={st.title}>Labor Planner</Text></View><ScrollView contentContainerStyle={st.scroll} keyboardShouldPersistTaps="handled">
 <View style={st.card}><Text style={st.h}>Today’s staffing plan</Text><Text style={st.muted}>Scheduled and actual hours are planning inputs. Flat-rate hours represent paid/flagged hours, not clock hours. Salary is not treated as an incremental hourly lever.</Text>{employees.map(e=><View key={e.id} style={st.emp}><View style={st.empHead}><View><Text style={st.name}>{e.employee_name}</Text><Text style={st.muted}>{e.pay_type.replace('_',' ')} · {e.pay_type==='salary'?formatCurrency(Number(e.pay_rate)): `${formatCurrency(Number(e.pay_rate))}/hr`}</Text></View></View><View style={st.row}><Field label="Scheduled" value={hours[e.id]??''} onChange={v=>setHours({...hours,[e.id]:v})}/><Field label={e.pay_type==='flat_rate'?'Paid/flagged':'Actual'} value={actual[e.id]??''} onChange={v=>setActual({...actual,[e.id]:v})}/></View></View>)}<Pressable style={st.button} disabled={saving} onPress={()=>void save()}><Text style={st.buttonText}>{saving?'Saving…':'Save staffing plan'}</Text></Pressable></View>
 <View style={st.card}><Text style={st.h}>What-If Simulator</Text><Text style={st.muted}>Choose a straight-hourly employee, then test a reduction in remaining paid hours.</Text><Text style={st.label}>Employee</Text><View style={st.chips}>{employees.filter(e=>e.pay_type==='straight_hourly').map(e=><Pressable key={e.id} onPress={()=>setCutEmployee(e.id)} style={[st.chip,cutEmployee===e.id&&st.chipOn]}><Text>{e.employee_name}</Text></Pressable>)}</View><Field label="Hours to reduce" value={cutHours} onChange={setCutHours}/><View style={st.metrics}><Metric label="Savings" value={formatCurrency(scenario.savings)}/><Metric label="Labor before" value={`${scenario.laborPctBefore.toFixed(2)}%`}/><Metric label="Labor after" value={`${scenario.laborPctAfter.toFixed(2)}%`}/><Metric label="MTD labor after" value={formatCurrency(scenario.laborAfter)}/></View>{goal!==null?<Text style={st.muted}>Labor goal: {goal.toFixed(2)}%. Current dollars above that goal at today’s MTD sales: {formatCurrency(scenario.dollarsToGoal??0)}.{selected&&scenario.hoursToGoalAtRate!==null?` At ${formatCurrency(Number(selected.pay_rate))}/hr, that is about ${scenario.hoursToGoalAtRate.toFixed(1)} straight-time hours.`:''}</Text>:null}<View style={st.notice}><Text style={st.noticeText}>Impact on sales: Not assumed.</Text><Text style={st.muted}>Use this only if workload allows. The app does not know future repair orders or available work.</Text></View></View>
 </ScrollView></SafeAreaView>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={st.field}><Text style={st.label}>{label}</Text><TextInput style={st.input} value={value} onChangeText={onChange} keyboardType="decimal-pad"/></View>}
function Metric({label,value}:{label:string;value:string}){return <View style={st.metric}><Text style={st.muted}>{label}</Text><Text style={st.metricV}>{value}</Text></View>}
const st=StyleSheet.create({page:{flex:1,backgroundColor:'#f5f7fa'},center:{flex:1,justifyContent:'center',alignItems:'center'},header:{padding:18,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:'#e3e8ef'},back:{color:'#1769e0',fontWeight:'800'},title:{fontSize:24,fontWeight:'900',color:'#14213d'},scroll:{padding:18,gap:14,paddingBottom:50},card:{backgroundColor:'#fff',padding:16,borderRadius:16,gap:12},h:{fontSize:19,fontWeight:'900',color:'#14213d'},muted:{color:'#637083',lineHeight:19},emp:{borderTopWidth:1,borderTopColor:'#edf1f6',paddingTop:12,gap:8},empHead:{flexDirection:'row',justifyContent:'space-between'},name:{fontWeight:'800',fontSize:16},row:{flexDirection:'row',gap:10},field:{flex:1,gap:5},label:{fontWeight:'700',color:'#34445c',fontSize:13},input:{borderWidth:1,borderColor:'#ccd5e0',borderRadius:10,padding:11,fontSize:16},button:{backgroundColor:'#1769e0',padding:14,borderRadius:11,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'900'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{padding:10,borderRadius:9,backgroundColor:'#edf1f6'},chipOn:{backgroundColor:'#bcd5ff'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{width:'48%',backgroundColor:'#f5f7fa',padding:12,borderRadius:10},metricV:{fontSize:19,fontWeight:'900',color:'#1769e0'},notice:{padding:12,borderRadius:10,backgroundColor:'#fff6df',gap:4},noticeText:{fontWeight:'900',color:'#704f00'}});
